# cattle|kubernetes|swarm|mesos
orchestrator: cattle
# https://hub.docker.com/r/rancher/server/tags/
version: latest
master:
  cpus: 1
  memory: 1024
server:
  count: 1
  cpus: 1
  memory: 2048
node:
  count: 3
  cpus: 1
  memory: 2048
ip:
  master: 172.22.101.100
  server: 172.22.101.101
  node:   172.22.101.111
net:
  private_nic_type: 82545EM
# Run a git server for local catalog service consumption
catalog:
  enabled: true
  host_repo_dirs: /Users/joliver/Workspace/llparse
  json: '{"catalogs":{"community":{"url":"http://172.22.101.100:4000/community-catalog","branch":"master"},"library":{"url":"http://172.22.101.100:4000/rancher-catalog","branch":"master"}}}'
  # TODO: transform yaml into json
  #
  # catalogs:
  #   library:
  #     url: http://172.22.101.100:4000/rancher-catalog
  #     branch: master
  #   community:
  #     url: http://172.22.101.100:4000/community-catalog
  #     branch: master
